version: '2.1'

services:
  mysql:
    build:
      context: ./docker_mysql
      args:
        - MYSQL_DATABASE=loopback
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.db/mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "6603:3306"
